name: Test, Lint, Deploy
on: push

jobs:
    test-stage:
        runs-on: ubuntu-latest
        steps:

            - name: Get the code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Communicate
              run: echo 'Set up underway...'

            - name: Communicate
              run: echo 'Delinting...'
            - name:
              run: npm run lint
            - name: Deploy
              run: npm run test
            - name: Communicate
              run: echo 'Deploying...'
            - name: Run it
              run: npm run build